services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: air_pollution
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d air_pollution"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build:
      context: ./air_quality_evolution_map
    container_name: django_app
    restart: always
    env_file: .env
    volumes:
      - ./air_quality_evolution_map:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

volumes:
  postgres_data: