# Generated by Django 6.0.2 on 2026-04-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementAgg',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('voivodeship', models.CharField(db_column='voivodeship', max_length=20)),
                ('pollutant', models.CharField(db_column='pollutant', max_length=20)),
                ('start_date', models.DateField(db_column='start_date')),
                ('avg_value', models.DecimalField(db_column='avg_value', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'measurement_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('voivodeship', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollutant', models.CharField(max_length=20)),
                ('measurement_date', models.DateField()),
                ('measurement_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('station', models.ForeignKey(db_column='station', on_delete=django.db.models.deletion.PROTECT, to='map.station')),
            ],
            options={
                'db_table': 'measurements',
            },
        ),
    ]
