# Generated by Django 6.0.2 on 2026-03-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pollutant', models.CharField(max_length=20)),
                ('measurement_date', models.DateField()),
                ('station', models.CharField(max_length=30)),
                ('measurement_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'measurements',
                'managed': False,
            },
        ),
    ]
