# Generated by Django 6.0.2 on 2026-05-04 20:59

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE MATERIALIZED VIEW measurement_agg AS
            SELECT
                s.voivodeship,
                m.pollutant,
                DATE_TRUNC('month', m.measurement_date)::date AS start_date,
                AVG(m.measurement_value) AS avg_value
            FROM measurements m
            JOIN stations s ON m.station = s.code
            GROUP BY
                s.voivodeship,
                m.pollutant,
                DATE_TRUNC('month', m.measurement_date)::date;
            """,
            reverse_sql="""
            DROP MATERIALIZED VIEW IF EXISTS measurement_agg;
            """
        ),

        migrations.RunSQL(
            sql="""
            CREATE UNIQUE INDEX idx_monthly_measurement_unique
            ON measurement_agg (voivodeship, pollutant, start_date);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_monthly_measurement_unique;
            """
        ),

        migrations.RunSQL(
            sql="""
            CREATE INDEX mv_monthly_lookup
            ON measurement_agg (pollutant, start_date);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS mv_monthly_lookup;
            """
        ),
    ]