# Generated by Django 6.0.2 on 2026-03-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyMeasurement',
            fields=[
                ('id', models.IntegerField(db_column='month_id', primary_key=True, serialize=False)),
                ('station', models.CharField(db_column='station', max_length=30)),
                ('pollutant', models.CharField(db_column='pollutant', max_length=20)),
                ('month_start', models.DateField(db_column='month_start')),
                ('avg_value', models.DecimalField(db_column='avg_value', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'monthly_measurement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YearlyMeasurement',
            fields=[
                ('id', models.IntegerField(db_column='year_id', primary_key=True, serialize=False)),
                ('station', models.CharField(db_column='station', max_length=30)),
                ('pollutant', models.CharField(db_column='pollutant', max_length=20)),
                ('year_start', models.DateField(db_column='year_start')),
                ('avg_value', models.DecimalField(db_column='avg_value', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'yearly_measurement',
                'managed': False,
            },
        ),
    ]
