# Generated by Django 6.0.2 on 2026-04-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementAgg',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('station', models.CharField(db_column='station', max_length=30)),
                ('pollutant', models.CharField(db_column='pollutant', max_length=20)),
                ('start_date', models.DateField(db_column='start_date')),
                ('avg_value', models.DecimalField(db_column='avg_value', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'measurement_agg',
                'managed': False,
            },
        ),
    ]
