# Generated by Django 6.0.2 on 2026-04-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_measurementagg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('voivodeship', models.CharField(max_length=20)),
            ],
        ),
    ]
