# Generated by Django 6.0.2 on 2026-05-15 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20260504_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollutant', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='LegendLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=15)),
                ('limit', models.FloatField()),
                ('color', models.CharField(max_length=20)),
                ('legend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='map.legend')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
