# Generated by Django 6.0.2 on 2026-05-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_legend_legendlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legendlevel',
            name='limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
