# Generated by Django 6.0.2 on 2026-04-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_station'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='station',
            table='stations',
        ),
    ]
