# Generated by Django 6.0.2 on 2026-05-15 17:58

from django.db import migrations

COLORS_5 = [
    "#57b108",
    "#b0dd10",
    "#ffd911",
    "#e50000",
    "#990000",
]

COLORS_6 = [
    "#57b108",
    "#b0dd10",
    "#ffd911",
    "#e58100",
    "#e50000",
    "#990000",
]

LEGENDS = {
    "SO2": {
        "limits": [50, 100, 200, 350, 500],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Dostateczny",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "µg/m³",
        "colors": COLORS_6,
    },

    "NO2": {
        "limits": [40, 100, 150, 230, 400],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Dostateczny",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "µg/m³",
        "colors": COLORS_6,
    },

    "O3": {
        "limits": [70, 120, 150, 180, 240],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Dostateczny",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "µg/m³",
        "colors": COLORS_6,
    },

    "PM10": {
        "limits": [20, 50, 80, 110, 150],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Dostateczny",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "µg/m³",
        "colors": COLORS_6,
    },

    "PM2.5": {
        "limits": [13, 35, 55, 75, 110],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Dostateczny",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "µg/m³",
        "colors": COLORS_6,
    },

    "As(PM10)": {
        "limits": [0.2, 0.5, 1, 2],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "ng/m³",
        "colors": COLORS_5,
    },

    "C6H6": {
        "limits": [1, 2, 3.5, 5],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "µg/m³",
        "colors": COLORS_5,
    },

    "Ni(PM10)": {
        "limits": [5, 10, 15, 20],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "ng/m³",
        "colors": COLORS_5,
    },

    "Pb(PM10)": {
        "limits": [0.1, 0.2, 0.35, 0.5],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "µg/m³",
        "colors": COLORS_5,
    },

    "BaP(PM10)": {
        "limits": [0.2, 0.5, 1, 2],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "ng/m³",
        "colors": COLORS_5,
    },

    "Cd(PM10)": {
        "limits": [1, 2, 3.5, 5],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "ng/m³",
        "colors": COLORS_5,
    },

    "CO": {
        "limits": [2, 4, 6, 10],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "mg/m³",
        "colors": COLORS_5,
    },

    "NO": {
        "limits": [20, 40, 80, 120],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "µg/m³",
        "colors": COLORS_5,
    },

    "IP": {
        "limits": [1, 2, 3, 5],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "-",
        "colors": COLORS_5,
    },

    "Hg": {
        "limits": [2, 5, 10, 20],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "ng/m³",
        "colors": COLORS_5,
    },

    "PAH_PM10": {
        "limits": [0.1, 0.3, 0.6, 1],
        "labels": [
            "Bardzo dobry",
            "Dobry",
            "Umiarkowany",
            "Zły",
            "Bardzo zły"
        ],
        "unit": "ng/m³",
        "colors": COLORS_5,
    },
}


def create_legends(apps, schema_editor):
    Legend = apps.get_model("map", "Legend")
    LegendLevel = apps.get_model("map", "LegendLevel")
    for pollutant, config in LEGENDS.items():
        legend, _ = Legend.objects.get_or_create(
            pollutant=pollutant,
            defaults={
                "unit": config["unit"]
            }
        )
        for index, label in enumerate(config["labels"]):
            if index < len(config["limits"]):
                limit = config["limits"][index]
            else:
                limit = None

            LegendLevel.objects.get_or_create(
                legend=legend,
                order=index + 1,
                defaults={
                    "label": label,
                    "limit": limit,
                    "color": config["colors"][index],
                }
            )


def delete_legends(apps, schema_editor):
    Legend = apps.get_model("map", "Legend")
    Legend.objects.filter(
        pollutant__in=LEGENDS.keys()
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('map', '0004_alter_legendlevel_limit'),
    ]

    operations = [
        migrations.RunPython(
            create_legends,
            delete_legends
        ),
    ]
