# Generated by Django 6.0.2 on 2026-04-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_station_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='outdated_code',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
